#!/bin/sh
set -e

test "$1" = 'purge' || exit 0

svc -x /etc/sv/tinydns 2>/dev/null || :
rm -rf /etc/sv/tinydns
rm -rf /var/lib/supervise/tinydns /var/lib/supervise/tinydns.log
for i in '@*' current config lock state; do
  rm -f /var/log/tinydns/$i
done
test ! -d /var/log/tinydns || rmdir /var/log/tinydns || :
! getent passwd Gtinydns >/dev/null || userdel -f Gtinydns || :
test -e /usr/share/debconf/confmodule || exit 0
. /usr/share/debconf/confmodule
db_purge
